### ISSUE TITLE
在docker-compose配置文件中可配置容器挂载数据集

### ISSUE THREAD

**Issue by Scisaga** [DvcLAB/JupyterLab-Inst#14]
## docker-compose配置文件修改
environment增加配置项datasets
`- datasets=${data_url_1},${data_url_2},${data_url_3}`

## 项目数据集配置文件 config/dataset.conf 格式修改
```
${data_url_1}
${data_url_2}
${data_url_3}
```

## 容器启动时执行逻辑修改
1. 使用配置文件中数据集配置项补全项目数据集配置文件
2. 在`/workspace/data/`创建数据集子文件夹，文件夹名称与数据集名称相同
3. 依次挂载数据集

**Comment by linstein** [comment]
数据集挂载的kafka消息应该如何定义：
1. 是每个数据集挂载后都发送一次挂载成功的消息
2. 还是整体数据集挂载完成后发送一次挂载成功消息
            --a. 如何判断所有数据集挂载成功
            --b. 如有挂载不成功的数据集应发送怎样的kafka信息

**Comment by linstein** [comment]
完成，且没加载成功一个数据集都会发送一条Kafka的msg

**Comment by Scisaga** [comment]
> 完成，且没加载成功一个数据集都会发送一条Kafka的msg

加载完全部数据集再发消息吧
